/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ractoc.fs.templates.editor.entity;

import com.ractoc.fs.parsers.entitytemplate.EntityTemplate;
import com.ractoc.fs.parsers.entitytemplate.TemplateWriter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author ractoc
 */
public class CreateEntityTemplateWizard extends javax.swing.JDialog {

    private File templateFile;

    /**
     * Creates new form CreateEntityTemplateWizard
     */
    public CreateEntityTemplateWizard(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public File create() {
        this.setVisible(true);
        return getTemplateFile();
    }

    private File getTemplateFile() {
        return templateFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        templateFileLocationLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        browseTemplateFileLocation = new javax.swing.JButton();
        templateFileLocation = new javax.swing.JTextField();
        jSplitPane3 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        templateName = new javax.swing.JTextField();
        errorMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Entity Template Wizard");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jSplitPane2.setDividerLocation(150);
        jSplitPane2.setDividerSize(0);

        templateFileLocationLabel.setText("Template Location");
        jSplitPane2.setLeftComponent(templateFileLocationLabel);

        jPanel3.setLayout(new java.awt.BorderLayout());

        browseTemplateFileLocation.setText("Browse");
        browseTemplateFileLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseTemplateFileLocationActionPerformed(evt);
            }
        });
        jPanel3.add(browseTemplateFileLocation, java.awt.BorderLayout.LINE_END);
        jPanel3.add(templateFileLocation, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane2);

        jSplitPane3.setDividerLocation(150);
        jSplitPane3.setDividerSize(0);

        jLabel1.setText("Template Name");
        jSplitPane3.setLeftComponent(jLabel1);
        jSplitPane3.setRightComponent(templateName);

        jPanel1.add(jSplitPane3);

        errorMessage.setForeground(java.awt.Color.red);
        jPanel1.add(errorMessage);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel4.add(finish);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel4.add(cancel);

        jPanel2.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseTemplateFileLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseTemplateFileLocationActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                templateFileLocation.setText(file.getCanonicalPath());
            } catch (IOException ex) {
                Logger.getLogger(CreateEntityTemplateWizard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_browseTemplateFileLocationActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        close();
    }//GEN-LAST:event_cancelActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        EntityTemplate template = new EntityTemplate(templateName.getText());
        TemplateWriter writer = new TemplateWriter();
        templateFile = new File(templateFileLocation.getText() + File.separator + templateName.getText() + ".etpl");
        if (templateFile.exists()) {
            errorMessage.setText("A template with that name already exists. Please choose a different name.");
        } else {
            writer.write(template, templateFileLocation.getText() + File.separator + templateName.getText() + ".etpl");
            close();
        }
    }//GEN-LAST:event_finishActionPerformed

    private void close() {
        templateFileLocation.setText("");
        templateName.setText("");
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseTemplateFileLocation;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextField templateFileLocation;
    private javax.swing.JLabel templateFileLocationLabel;
    private javax.swing.JTextField templateName;
    // End of variables declaration//GEN-END:variables
}
